DROP TABLE IF EXISTS Concert;

DROP TABLE IF EXISTS Song;
CREATE TABLE Song (
songId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
songName VARCHAR(255)
);

DROP TABLE IF EXISTS Album;
CREATE TABLE Album (
albumId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
albumName VARCHAR(255)
);

DROP TABLE IF EXISTS Band;
CREATE TABLE Band (
bandId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
bandName VARCHAR(255)
);

DROP TABLE IF EXISTS Artist;
CREATE TABLE Artist (
artistId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
artistName VARCHAR(255)
);

INSERT INTO Song (
    songName
) VALUES (
	"brandnewsong"
);

SELECT * FROM Song;